version: "3.9"

services:
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    ports:
      - "8081:8081"
      - "5000:5000"
    volumes:
      - /mnt/core_data/docker/nexus:/opt/sonatype/sonatype-work
    environment:
      - TZ=Europe/Warsaw
    restart: always
    networks:
      - nexus

networks:
  nexus:
    name: nexus
    driver: bridge